data_dir: ''

irishjobs_html_data_dir: 'irishjobs_raw_data'
irishjobs_filename_added: 'irishjobs_data_added.csv'
irishjobs_filename: "irishjobs_data.csv"

linkedin_html_data_dir: "linkedin_raw_data"
linkedin_filename_added: 'linkedin_data_added.csv'
linkedin_filename: 'linkedin_data.csv'

main_table_path: 'all_jobs.csv'
job_alert_path: '1_job_alert_recommendation.csv'
recommendation_path: '2_today_recommendation.csv'
all_today_new_open_jobs: '3_other_today_new_open_jobs.csv'

title_filter_keywords: "AI,ML,Data,software,senior,engineer"
delete_words_in_title: "trainee,affairs,grain,part-time,part time,intern,product"
delete_words_in_company: "human,recruitment,jobgether,recruit,fruition,talent"

interview_company: "acompany,bcompany"
similar_company_save_path: "similar_company_list.csv"
region: "Ireland"
top_k: int("recommend number for similar business companies based on your interview_company")





