apply_data_path: "applied_data/"
save_file: "applied_data/last_apply_data.csv"

data_dir: './'

irishjobs_html_data_dir: 'irishjobs_raw_data'
irishjobs_filename_added: 'irishjobs_data_added.csv'
irishjobs_filename: "irishjobs_data.csv"

linkedin_html_data_dir: "linkedin_raw_data"
linkedin_filename_added: 'linkedin_data_added.csv'
linkedin_filename: 'linkedin_data.csv'

main_table_path: 'all_jobs.csv'
recommendation_path: 'today_recommendation.csv'
job_alert_path: 'job_alert_recommendation.csv'
